# pact new project_name -l py -t personal
# This will create a new dir inside $HOME/dev/personal/python/project_name
# Run pre stuff like logging, doesnt neeed to be present
# Main stuff is when its already inside that dir, so like copying templates etc
# post is for running after its done. meaning to eg start a virtual venv env for
# example when tmux is initiated in headless state already.
# Meaning that all common run before config specific ones :)
# I want the config to be as simple as, yet flexible as possible
base_dir: "$HOME/dev/"
shell: "$SHELL"

types:
  p: "personal"
  w: "work"
  s: "school"
  t: "scratch"

common:
  pre:
    - "echo 'Scaffolding for project {{project_name}} in {{project_dir}} for type {{project_type}}'"
  main:
    - "echo 'Running main already inside the the newly created dir!'"
    - "cp 'copy templates like common readme'"
    - "git init"
  post:
    - "tmux"

new:
  py:
    dir: "python"
    pre:
      - "touch hello.py README.md"
    main:
      - "python3 -m venv .venv"
    post:
      - "source .venv/bin/activate"
  
  rs:
    dir: "rust"
    main:
      - "cargo init"

clone:
  default:
    main:
      - clone:
    
